apiVersion: v1
kind: Service
metadata:
    name: my-service
    labels:
      app: my-app
    # Set Loadbalancer as external
    annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007